const $ = selector => document.querySelector(selector);
let user, threadId = null, busy = false;
const labels = {intake:'理解与分类 / Intake',evidence:'知识检索 / Evidence',recall:'会话记忆 / Recall',priority:'影响分级 / Priority',draft:'生成建议 / Draft',review:'最终审查 / Review'};
const escape = text => String(text ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
async function api(url, options={}) {const response=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});let body;try{body=await response.json()}catch{body={detail:'Unexpected server response'}}if(!response.ok)throw Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));return body;}
function showWorkspace(account){user=account;$('#login-screen').hidden=true;$('#workspace').hidden=false;$('#ops-nav').hidden=user.role!=='engineer';$('#account-label').textContent=user.username+' · '+user.role;$('#mode-label').textContent=user.model_mode==='ollama'?'Ollama · 真实模型':'规则演示 / Demo';}
$('#login-form').onsubmit=async event=>{event.preventDefault();$('#login-error').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});showWorkspace(await api('/api/me'))}catch(error){$('#login-error').textContent=error.message}};
$('#use-engineer').onclick=()=>{$('#username').value='engineer';$('#password').value='engineer-demo-only'};
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.view').forEach(view=>view.hidden=true);$('#'+button.dataset.view+'-view').hidden=false;document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));$('#page-label').textContent=button.textContent;if(button.dataset.view==='tickets')loadTickets();if(button.dataset.view==='operations')loadOperations()});
document.querySelectorAll('[data-prompt]').forEach(button=>button.onclick=()=>{$('#message').value=button.dataset.prompt;$('#message').focus()});
function resetTrace(){ $('#trace').innerHTML=Object.entries(labels).map(([key,label])=>`<li data-node="${key}">${label}</li>`).join('');$('#sources').textContent='';$('#decision').innerHTML='<p>正在处理 / Processing…</p>'; }
$('#new-thread').onclick=()=>{if(busy)return;threadId=null;$('#messages').innerHTML='<div class="empty-state"><h2>新会话已准备好</h2><p>New conversation ready.</p></div>';resetTrace();$('#decision').textContent='等待提交 / Ready';};
function bubble(text,role){const element=document.createElement('div');element.className='bubble '+role;element.textContent=text;$('#messages .empty-state')?.remove();$('#messages').append(element);$('#messages').scrollTop=$('#messages').scrollHeight;return element;}
function progress(event){const element=$(`[data-node="${event.node}"]`);if(element){element.classList.toggle('running',event.phase==='started');element.classList.toggle('done',event.phase==='complete');element.textContent=labels[event.node]+(event.elapsed_ms!=null?` · ${event.elapsed_ms}ms`:'');}}
function completed(state,element){if(state.phase==='FAILED')throw Error(state.outcome.error);const result=state.outcome;element.innerHTML=escape(result.answer).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');state.events.forEach(progress);$('#decision').innerHTML=`<span class="pill ${escape(result.priority.level)}">${escape(result.priority.level)}</span><span class="pill">${escape(result.intake.intent)}</span><p>${escape(result.priority.explanation)}</p><p>审查 ${result.review.replacement_used?'已替换不安全草稿':'已完成'} · ${result.model_mode==='ollama'?'真实模型':'规则演示'}</p><p>${result.degraded.length?'模型调用降级：'+escape(result.degraded.join(', ')):''}</p><p>${result.intake.intent==='FAQ'?'无需工单 / No ticket':'工单操作已排队，可前往工单记录查看 / Actions queued'}</p>`;$('#sources').innerHTML=result.evidence.map(item=>`<div class="source"><strong>${escape(item.title)}</strong><small>${escape(item.source)} · ${escape(item.channels.join(' + '))}</small></div>`).join('');$('#messages').scrollTop=$('#messages').scrollHeight;}
async function watchSSE(id,element){return new Promise((resolve,reject)=>{const stream=new EventSource(`/api/operations/${id}/events`);let text='';stream.addEventListener('progress',event=>progress(JSON.parse(event.data)));stream.addEventListener('answer',event=>{text+=JSON.parse(event.data).text;element.textContent=text;});stream.addEventListener('complete',event=>{stream.close();try{completed(JSON.parse(event.data),element);resolve()}catch(error){reject(error)}});stream.onerror=()=>{stream.close();reject(Error('进度连接中断；可刷新工单记录或查询操作。 / Progress connection interrupted.'))};});}
async function watchMCP(id,element){for(let count=0;count<360;count++){const response=await api('/api/simulated-assistant/'+id);$('#transport-status').textContent=`MCP ${response.protocol} · ${response.tool}`;const state=response.result;state.events.forEach(progress);if(state.phase!=='RUNNING'){completed(state,element);return}await new Promise(resolve=>setTimeout(resolve,1000))}throw Error('处理时间较长，请稍后刷新工单。 / Still processing.');}
$('#support-form').onsubmit=async event=>{event.preventDefault();if(busy)return;const message=$('#message').value.trim();if(!message)return;busy=true;$('#send').disabled=true;$('#support-error').textContent='';bubble(message,'user');const answer=bubble('正在检索并处理 / Working…','assistant');resetTrace();try{const viaMCP=$('#transport').value==='mcp';const body={message,request_id:crypto.randomUUID(),...(threadId?{thread_id:threadId}:{})};const response=await api(viaMCP?'/api/simulated-assistant':'/api/support',{method:'POST',body:JSON.stringify(body)});const operation=viaMCP?response.result:response;threadId=operation.thread_id;$('#message').value='';if(viaMCP){$('#transport-status').textContent=`MCP ${response.protocol} · Streamable HTTP`;await watchMCP(operation.operation_id,answer)}else{await watchSSE(operation.operation_id,answer)}}catch(error){answer.textContent='处理未完成 / Processing incomplete';$('#support-error').textContent=error.message}finally{busy=false;$('#send').disabled=false;}};
function table(headings,rows){return `<div class="table-wrap"><table><thead><tr>${headings.map(item=>`<th>${escape(item)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
async function loadTickets(){try{const tickets=await api('/api/tickets');$('#ticket-list').innerHTML=tickets.length?tickets.map(ticket=>`<article class="ticket"><div class="ticket-header"><h2>${escape(ticket.reference)}</h2><div><span class="pill ${escape(ticket.priority)}">${escape(ticket.priority)}</span><span class="pill">${escape(ticket.phase)}</span></div></div><p>${escape(ticket.summary)}</p><p>${escape(ticket.category)} · 负责人 ${escape(ticket.assignee||'待分配')} · UTC ${escape(ticket.created)}</p>${ticket.notes.map(note=>`<div class="notes"><p>${escape(note.author)} · ${escape(note.phase)}</p><p>${escape(note.text)}</p></div>`).join('')}${user.role==='engineer'&&ticket.phase!=='RESOLVED'?`<form data-ticket="${escape(ticket.id)}" data-revision="${ticket.revision}"><textarea name="note" placeholder="填写排查进展或解决记录 / Processing note" required maxlength="2000"></textarea><div><select name="phase"><option value="INVESTIGATING">处理中</option><option value="RESOLVED">已解决</option></select><button type="submit">保存更新 / Save</button></div></form>`:''}</article>`).join(''):'<section class="panel"><h2>暂无工单 / No work orders</h2><p>知识咨询不会建单；故障工单将在队列执行后出现。</p></section>';document.querySelectorAll('[data-ticket]').forEach(form=>form.onsubmit=async event=>{event.preventDefault();try{await api('/api/tickets/'+form.dataset.ticket,{method:'PATCH',body:JSON.stringify({note:form.elements.note.value,phase:form.elements.phase.value,expected_revision:Number(form.dataset.revision)})});await loadTickets()}catch(error){$('#ticket-error').textContent=error.message}})}catch(error){$('#ticket-error').textContent=error.message}}
$('#refresh-tickets').onclick=loadTickets;
async function loadOperations(){try{const [runtime,knowledge]=await Promise.all([api('/api/diagnostics'),api('/api/knowledge')]);$('#runtime-cards').innerHTML=[['数据库',runtime.database],['Redis',runtime.redis?'已连接':'SQL 回退'],['向量索引',runtime.vector.ready?'Ready':'未就绪'],['知识 / Skills',`${runtime.segments} / ${runtime.skills.length}`]].map(([label,value])=>`<div class="metric"><small>${escape(label)}</small><strong>${escape(value)}</strong></div>`).join('');$('#knowledge-list').innerHTML=table(['文档','片段'],Object.entries(knowledge.documents).map(([name,count])=>`<tr><td>${escape(name)}</td><td>${count}</td></tr>`));$('#action-list').innerHTML=table(['工具','阶段','尝试','错误'],runtime.actions.map(action=>`<tr><td>${escape(action.kind)}</td><td>${escape(action.phase)} ${action.phase==='DEAD'?`<button data-retry="${escape(action.id)}">重试</button>`:''}</td><td>${action.tries}</td><td>${escape(action.error)}</td></tr>`));document.querySelectorAll('[data-retry]').forEach(button=>button.onclick=async()=>{try{await api('/api/actions/'+button.dataset.retry+'/retry',{method:'POST'});loadOperations()}catch(error){$('#ops-error').textContent=error.message}});$('#audit-list').innerHTML=table(['工具操作','尝试','结果','传输'],runtime.audits.map(item=>`<tr><td>${escape(item.action_id.slice(0,10))}</td><td>${item.attempt}</td><td>${escape(item.result)}</td><td>${escape(item.transport)}</td></tr>`))+`<p class="footnote">升级通知：${escape(JSON.stringify(runtime.receipts.filter(item=>item.kind==='escalation')))}</p>`;$('#rebuild').disabled=!runtime.vector.enabled;}catch(error){$('#ops-error').textContent=error.message}}
$('#refresh-ops').onclick=loadOperations;
$('#upload-form').onsubmit=async event=>{event.preventDefault();const form=new FormData();form.append('file',$('#document').files[0]);try{const result=await api('/api/knowledge',{method:'POST',body:form});$('#knowledge-status').textContent=`已导入 ${result.segments} 个片段。${result.rebuild_required?'请重建向量索引。':''}`;loadOperations()}catch(error){$('#ops-error').textContent=error.message}};
$('#rebuild').onclick=async()=>{$('#rebuild').disabled=true;$('#knowledge-status').textContent='正在重建 / Rebuilding…';try{await api('/api/knowledge/rebuild',{method:'POST'});$('#knowledge-status').textContent='向量索引已就绪 / Vector index ready';await loadOperations()}catch(error){$('#ops-error').textContent=error.message}finally{$('#rebuild').disabled=false}};
api('/api/me').then(showWorkspace).catch(()=>{});
